### ISSUE TITLE
sniffer.py error

### ISSUE THREAD

**Issue by xup62j4** [hsttw/SHIT#4]
Traceback (most recent call last):
  File "./sniffer.py", line 79, in <module>
    sniff(iface=interface, filter="tcp and port 80", prn=http_handler, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "./sniffer.py", line 62, in http_handler
    if headers["Content-Type"] == "application/x-www-form-urlencoded":
  File "/usr/lib/python2.7/rfc822.py", line 388, in **getitem**
    return self.dict[name.lower()]
KeyError: 'content-type'

**Comment by oscar3x39** [comment]
Fixed in 2a06350. http_handler used `headers["Content-Type"]` directly, so a POST without that header raised KeyError and killed the whole sniff loop. Switched to `headers.get("Content-Type")` which degrades to None instead of throwing.
